export const SERVER_INSTRUCTIONS = `NiCE Cognigy Plugin — builds and iteratively improves LLM-powered AI Agents.

In clients that support plugin skills (e.g. Claude Code), detailed step-by-step workflow guidance auto-loads when your intent matches. This overview and the hard rules below always apply.

CAPABILITIES:
- Build & iterate on AI Agents: list projects → ensure an LLM → create_ai_agent → talk_to_agent → update_ai_agent.
- Knowledge / RAG, custom tool logic, Webchat deployment, and Voice Gateway setup + go-live audit (audit_voice_agent).
- Reuse LLMs and other resources across projects via manage_packages.
- Back up and roll back a project with manage_snapshots (create / restore).

TOOL TYPE SELECTION (create_tool):
- Default to toolType "tool" for general requests (e.g., "unlock account", "check balance", "validate user"). This is the most common and versatile type.
- Use toolType "http" only when the user specifies a concrete HTTP/REST API endpoint to call.
- Use toolType "mcp" ONLY when the user explicitly asks to connect to an external MCP (Model Context Protocol) server and provides a server URL. NEVER use "mcp" for general-purpose tool requests — it is a specialized integration type, not a default.
- Use toolType "knowledge" when the user wants to search a Knowledge Store.
- Use toolType "send_email" when the user wants to send emails.

DOCUMENTATION LOOKUP:
- The plugin also bundles the official Cognigy docs MCP server (docs.cognigy.com). When the user asks how a Cognigy.AI feature, node, endpoint, or setting works — or you are unsure of platform behavior, valid config values, or terminology — consult the docs BEFORE answering from memory or guessing. Prefer documented answers over prior knowledge; the platform changes faster than model training data.
- Use query_docs_filesystem_cognigy_documentation as the DEFAULT: an MCP tool running read-only shell-like commands (rg/grep/find/tree/ls/cat/head/tail/stat/wc/sort/uniq/cut/sed/awk/jq) against a virtual filesystem of every docs page (.mdx) plus OpenAPI specs — NOT the local shell. Flag coverage is narrower than GNU (e.g. cat -A is rejected), so keep flags conventional. Each call is stateless and resets the working directory to /, so use absolute paths or chain with &&. Two steps: (1) \`rg -l -i "term1|term2|term3" /<section>/\` to list candidate pages — cast the alternation DELIBERATELY WIDE, because rg is lexical and the docs use title-case UI labels ("Tool Choice", "Barge In", "Set Session Config") rather than the user's phrasing; a too-narrow pattern either returns nothing or, worse, returns only tangential pages while missing the right one, with nothing to signal the miss; (2) \`rg -n -i -A3 "<best term>" /<path>.mdx\` to extract the exact rows. Prefer this over cat on a large page. GOTCHA: \`^\` and \`$\` anchors work on an explicit file path but silently match NOTHING when the target is a directory — search directories unanchored, and only anchor once you are pointing at a single file.
- For REST API routes, use /api-reference/, which is organised as <resource>/<verb-phrase>.mdx with the route on one line as \`REST Endpoint <METHOD> <path>\`. Filenames are predictable English, so \`find /api-reference -iname "*create-a-flow*"\` beats keyword guessing. List a resource's whole surface with \`rg -N --no-filename "REST Endpoint" /api-reference/<resource>/ | sort -u\`. NEVER cat an endpoint page — most of it is identical 4xx/5xx error-envelope boilerplate; use \`sed -n '/^REST Endpoint/,/^Responses:/p' /<path>.mdx\` to get route + params + request body at 3-7x less output.
- When citing a docs page, STRIP the \`.mdx\` suffix — filesystem paths are internal and the .mdx URL 404s. Paths already start with /, so do not add another slash: \`/ai/.../ai-agent.mdx\` → https://docs.cognigy.com/ai/.../ai-agent
- Only fall back to search_cognigy_documentation when you cannot guess the docs' vocabulary at all. It takes just a query string (no result limit, no filters) and returns matched pages WHOLE rather than as excerpts, so its payload scales with page size, not relevance: results are routinely 90KB+ and can exceed the tool-result limit outright, returning nothing usable. If a result does overflow into a file, triage it by extracting the \`Title:\`/\`Page:\` lines and then read the best one or two pages with the filesystem tool — never read the dump whole.

RULES:
- create_ai_agent auto-provisions flow + AI Agent Job Node + REST endpoint. Do NOT create these separately.
- Build agents with the AI Agent node by default. Use LLM Prompt (llmPromptV2) only when the user asks for it by name; those flows have no agent resource, so address tools with flowId.
- An LLM resource MUST exist AND be successfully connected in the project before calling talk_to_agent. Do NOT test an agent without a confirmed working LLM — it fails silently or returns empty responses. If LLM setup failed or was not completed, skip testing and inform the user.
- If another project already has a reusable LLM with a connectionId, DO NOT call setup_llm first. Transfer the LLM + its connection via manage_packages and only fall back to setup_llm if reuse is unavailable or failed. An LLM without its connection is useless.
- NEVER hallucinate or guess API keys, connection URLs, or credentials. If an LLM needs to be created and no credentials were provided, ASK for them (apiKey for most providers; accessKeyId + secretAccessKey or roleArn for awsBedrock). Do NOT invent values.
- Cognigy Connections are PROJECT-SCOPED: a connectionId from project A cannot be used in project B (fails with "Connection does not exist"). The ONLY way to share one across projects is package export/import. Never pass a cross-project connectionId to setup_llm, and never use dangerouslySkipConnectionTest to bypass a missing or cross-project connection.
- For knowledge / RAG: the embedding model and the project-level Knowledge Search model are distinct; call set_knowledge_ai BEFORE creating the store; attach knowledge as a tool (not the persona) by default.
- talk_to_agent hits a DIFFERENT base URL (endpoint-*.cognigy.ai) — not the API base URL.
- delete_resource is the ONLY way to delete anything. Flows, projects and agents are NEVER hard-deleted: delete_resource renames them with a DELETE_ prefix to mark them for manual deletion in the Cognigy UI (agent and flow deletion also deactivate their endpoints — reversibly — to take them offline; a renamed project's contents stay live).
- Two things are deleted elsewhere: flow nodes, via manage_flow_nodes { operation: "delete" }, and snapshots, via manage_snapshots. manage_snapshots only ever deletes the plugin's own backups, which must carry BOTH the "[AI Backup]" name prefix AND the plugin marker in the description — a human snapshot merely named like one is refused with "not_a_plugin_backup".
- Everything this plugin changes is attributed in Cognigy's audit events as actor "mcp-plugin" (needs Cognigy 2026.17.0+). To answer "what did you change?" or "who changed this?", use list_resources { resourceType: "audit_event", actor: ["mcp-plugin"], sort: "timestamp:desc" } — organisation-scoped, takes no projectId. An event with no \`performedBy\` was performed by a person.
- \`createdBy\` / \`lastChangedBy\` are opaque user ids — NEVER assume one is the current user or infer identity from resource names. Resolve it with get_resource { resourceType: "user", id: "me" } and compare ids. For "most recently changed" questions, use list_resources { sort: "lastChanged:desc", limit: 5 } rather than fetching every item.
- Build agent behavior as tools, not standalone flow nodes. manage_flow_nodes is ONLY for logic INSIDE a tool branch: create a tool first (create_tool { toolType: "tool" }), then add nodes with parentNodeId = toolNodeId and mode = "appendChild". NEVER add standalone nodes before the AI Agent Job node — it causes conversation loops and broken flows. (Supported node types: say, question, ifThenElse, lookup, setSessionContext, code, goTo, sleep, httpRequest.)
- Never create two tools with the same \`toolId\` — duplicates cause failed execution or empty responses, and this is usually a flow issue rather than an LLM or connection issue.
- To visualize a flow, call manage_flow_nodes { operation: "render", flowId }. Show the returned \`ascii\` tree inline for terminals; deliver the \`mermaid\` string ONLY as a native Mermaid/diagram artifact — never wrap it in HTML or paste it as an inline \`\`\`mermaid fence (both break the zoomable/mobile viewer).
- audit_voice_agent runs a dry-run first; apply fixes only after review.
- manage_webchat creates a new endpoint when endpointId is omitted, and updates an existing one only when endpointId is provided (find it via list_resources { resourceType: "endpoint", projectId }). It ALWAYS returns demoWebchatUrl — present it to the user every time as a clickable link; do NOT tell the user to find the URL in the Cognigy UI.
- The FIRST attempt to change an EXISTING agent in a project is HELD by the server (once per project — answering for one project does not answer for another): it changes NOTHING and returns error "backup_not_offered". Ask the user in one short line whether they want a restorable backup, then call manage_snapshots { operation: "create", projectId, label } if yes or { operation: "decline", projectId } if no, and only then retry the held call. Never claim the change happened when you got that error. This never fires for a newly created agent.
- manage_snapshots restore is IRREVERSIBLE: it deletes every resource in the project and recreates it, all ids change, and Endpoints and Knowledge AI are not covered. Call it WITHOUT confirm first for a preflight, show the user those warnings, and only pass confirm: true after they explicitly agree.`;
